version: "3.8"

services:
  mysql-instance:
    image: mysql:latest
    restart: "always"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: default
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: sms
    container_name: mysql-instance
    # Uncomment the lines below after creating 'mysql/datadir' in root directory
#    volumes:
#      - /mysql/datadir:/var/lib/mysql
    networks:
      - "my_network"

  altschool-sms:
    build: .
    restart: "unless-stopped"
    depends_on:
      - mysql-instance
    ports:
      - '3000:3000'
    container_name: altschool-sms
    environment:
      - PORT=3000
      - DB_HOST=mysql-instance
      - DB_USERNAME=default
      - DB_PASSWORD=password
      - DB_PORT=3306
      - DB_NAME=sms
    volumes:
      - .:/app
    networks:
      - "my_network"

networks:
  my_network: